name: coverage

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
      
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Get Cover 
            uses: orgoro/coverage@v3.1
            with:
                coverageFile: junit/test-results.xml
                token: ${{ secrets.GITHUB_TOKEN }}