# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    name: Run tests & display results
    runs-on: ubuntu-latest
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
      actions: read
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Poetry
        run: |
          pipx install poetry --python=python3.10

      - name: Poetry caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/
          key: ${{ hashFiles('poetry.lock') }}

      - name: Install deps
        run: poetry install


      - name: Test with pytest
        env: 
          API_KEY: ${{ secrets.API_KEY }}
          COVERAGE_FILE: .coverage
        run: |
          pip install pytest pytest-cov
          python setup.py bdist_wheel --universal
          poetry run pytest

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_PR_RUN_ID: ${{ inputs.GITHUB_PR_RUN_ID }}
          COMMENT_ARTIFACT_NAME: python-coverage-comment-action
          COMMENT_FILENAME: python-coverage-comment-action.txt
          

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v3
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: ./coverage_comment/python-coverage-comment-action.txt

          