# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    name: Run tests & display results
    runs-on: ubuntu-latest
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
      actions: read
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install exceptiongroup
          pip install -r requirements.txt

      - name: Install Poetry
        run: |
          pipx install poetry --python=python3.11

      - name: Poetry caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/
          key: ${{ hashFiles('poetry.lock') }}

      - name: Install deps
        run: poetry install

      - name: Run tests
        id: coverage_comment
        env: 
          API_KEY: ${{ secrets.API_KEY }}
          COVERAGE_COMMENT_E2E_ACTION_REF: ${{ github.sha }}
          COVERAGE_COMMENT_E2E_REPO_SUFFIX: ${{ github.event.number }}
          COVERAGE_COMMENT_E2E_PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: poetry run pytest --cov=weekend_api

      - name: Coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          ANNOTATE_MISSING_LINES: true

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v3
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt

          